---

- hosts: localhost
  connection: local

  tasks:
    - name: install latest versions of development tools
      dnf: name={{ item }} state=latest
      with_items:
        - git
        - gcc
        - emacs
        - ipython
      become: true
      become_user: root

    - name: install python packages
      pip: name={{ item }} state=latest
      with_items:
        - elpy
        - rope
        - jedi
        - epc
        - flake8
        - importmagic
        - autopep8
        - yapf
      become: true
      become_user: root

    - name: install xmonad and mate as desktop environment
      dnf: name={{ item }} state=latest
      with_items:
        - xmonad
        - xmonad-mate
        - ghc-xmonad-contrib-devel
        - xmonad-log-applet-mate
        - mate-themes
        - mate-icon-theme-faenza
        - mate-power-manager
        - network-manager-applet
        - gnome-terminal
        - conky
        - evince
      become: true
      become_user: root

    - name: install latex
      dnf: name={{ item }} state=latest
      with_items:
        - texlive
        - texlive-t2
        - texlive-was
        - texlive-minted
        - texlive-collection-langcyrillic
      become: true
      become_user: root

    - name: create directories
      file: path=~/{{ item }} state=directory mode=0755
      with_items:
        - .xmonad
        - projects/prde

    - name: set global git options
      shell: git config --global {{ item.name }} {{ item.value }}
      with_items:
        - { name: 'core.autocrlf', value: 'input' }
        - { name: 'push.default', value: 'current' }

    - name: get latest versions of prde components
      git: repo={{ item.repo }} dest=~/projects/prde/{{ item.dest }} update=yes clone=yes
      with_items:
        - { repo: 'https://github.com/prde/prde-xmonad-config.git', dest: 'prde-xmonad-config' }
        - { repo: 'https://github.com/prde/prde-emacs-config.git', dest: 'prde-emacs-config' }
        - { repo: 'https://github.com/prde/prde-install-fedora.git', dest: 'prde-install-fedora' }
      ignore_errors: yes

    - name: create component links
      file: src=~/projects/prde/{{ item.src }} dest=~/{{ item.dest }} state=link
      with_items:
        - { src: 'prde-xmonad-config/xmonad-fedora.hs', dest: '.xmonad/xmonad.hs' }
        - { src: 'prde-xmonad-config/conkyrc', dest: '.conkyrc' }
        - { src: 'prde-xmonad-config/prde.png', dest: '.xmonad/wallpaper.png' }
        - { src: 'prde-emacs-config', dest: '.emacs.d' }
        - { src: 'prde-emacs-config/flake8', dest: '.config/flake8' }
      ignore_errors: yes

    - name: set background
      shell: gsettings set org.mate.background {{ item.key }} "{{ item.value }}"
      with_items:
        - { key: 'picture-options', value: 'centered' }
        - { key: 'color-shading-type', value: 'solid' }
        - { key: 'picture-filename', value: '{{ ansible_env.HOME }}/.xmonad/wallpaper.png' }
        - { key: 'primary-color', value: '#000000000000' }
        - { key: 'secondary-color', value: '#3c3c8f8f2525' }

    - name: set gtk theme
      shell: gsettings set org.mate.interface gtk-theme "Blue-Submarine"

    - name: set default editor
      shell: '{{ item }}'
      with_items:
        - '[ "$(grep EDITOR ~/.bashrc)" ] || echo "export EDITOR=\"emacsclient -c\"" >> ~/.bashrc'
        - 'xdg-mime default emacsclient.desktop $(grep "^text/x-*" /usr/share/mime/types)'
